baseURL = 'https://blog.ioputting.com/'
languageCode = 'zh-cn'
title = '输入输出'
theme= 'PaperMod'

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  homeInfoParams:
    Title: Hi there 
    Content: [email](mailto:hi@ioputting.com)
